### ISSUE TITLE
Getting parse error during usage

### ISSUE THREAD

**Issue by bhudlemeyer** [pivotal-cf/bosh-creds-resource#1]
![image](https://user-images.githubusercontent.com/2275490/30516979-0c9ca858-9b04-11e7-99e8-fc632c6a19a2.png)

**Comment by UWTech** [comment]
I'm seeing the same thing. Did anyone find a cause and solution?

**Comment by nshrest3** [comment]
may be in the pipeline for bosh-creds resource, u have used the opsman url instead of a hostname (fqdn)

**Comment by UWTech** [comment]
That was the problem, thank Niraj.
